hugoblox:
  schema: "2.0"
  identity:
    name: Xiangyu Zhou
    type: person
    tagline: Graduate Research Assistant | Wayne State University
    description: Xiangyu Zhou is currently advancing as a Ph.D. candidate in the Department of Computer Science at Wayne State University.
  theme:
    mode: system
    pack: default
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: serif
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
